'use strict';
const http=require('http'),fs=require('fs'),path=require('path');
function loadDotEnv(file=path.join(process.cwd(),'.env')){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const x=line.trim();if(!x||x.startsWith('#'))continue;const i=x.indexOf('=');if(i<1)continue;const key=x.slice(0,i).trim();let value=x.slice(i+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);if(!(key in process.env))process.env[key]=value}}loadDotEnv();
const PORT=Number(process.env.PORT||3000),PROVIDER=String(process.env.AI_PROVIDER||'openrouter').toLowerCase(),MODEL=process.env.AI_MODEL||(PROVIDER==='openai'?'gpt-4.1':'~openai/gpt-latest'),OPENAI_API_KEY=process.env.OPENAI_API_KEY||'',OPENROUTER_API_KEY=process.env.OPENROUTER_API_KEY||'',ALLOWED_ORIGINS=String(process.env.ALLOWED_ORIGIN||'https://kclsurvey.github.io,http://localhost:3000,http://127.0.0.1:3000').split(',').map(x=>x.trim()).filter(Boolean),MAX_BODY_BYTES=Number(process.env.MAX_BODY_BYTES||2000000),MAX_REQUESTS_PER_MINUTE=Number(process.env.MAX_REQUESTS_PER_MINUTE||30),buckets=new Map();
function isAllowedOrigin(origin){if(!origin)return true;return ALLOWED_ORIGINS.includes('*')||ALLOWED_ORIGINS.includes(origin)}function corsHeaders(origin){const allow=ALLOWED_ORIGINS.includes('*')?'*':(isAllowedOrigin(origin)?origin:ALLOWED_ORIGINS[0]);return {'Access-Control-Allow-Origin':allow,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Private-Network':'true','Vary':'Origin','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}function sendJson(res,status,body,origin=''){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{...corsHeaders(origin),'Content-Type':'application/json; charset=utf-8','Content-Length':data.length});res.end(data)}function rateAllowed(ip){const now=Date.now(),minute=60000,item=buckets.get(ip);if(!item||now-item.started>=minute){buckets.set(ip,{started:now,count:1});return true}item.count+=1;return item.count<=MAX_REQUESTS_PER_MINUTE}function readJson(req){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>MAX_BODY_BYTES){reject(Object.assign(new Error('Request body is too large'),{statusCode:413}));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch{reject(Object.assign(new Error('Invalid JSON body'),{statusCode:400}))}});req.on('error',reject)})}
const actionTypes=['none','set_input','set_param','set_global','set_product','set_channel','set_expense','set_sku','set_cash'];
const actionSchema={type:'object',additionalProperties:false,properties:{type:{type:'string',enum:actionTypes},target:{type:'string'},field:{type:'string'},value_text:{type:'string'},reason:{type:'string'}},required:['type','target','field','value_text','reason']};
const responseSchema={type:'object',additionalProperties:false,properties:{answer:{type:'string'},warnings:{type:'array',items:{type:'string'}},actions:{type:'array',items:actionSchema}},required:['answer','warnings','actions']};
const instructions=`Ты — AI-консультант внутри калькуляторов маржи v9.1 и бизнес-модели v10.1.
Пользователь не финансист и не бухгалтер. Отвечай на русском языке простыми словами, без лишней терминологии.
Используй ТОЛЬКО snapshot калькулятора. Не придумывай отсутствующие расходы, рыночные цены, законы, льготы или факты.
Если вопрос о параметре или показателе, ответ обязательно разделяй заголовками:
Что это
Текущий показатель
Как рассчитывается
На что влияет
Что будет при ошибке или пропуске
Как использовать
Где найти
Если вопрос об общей выгодности, ответ разделяй заголовками:
Главный вывод
Текущий результат
Почему такой вывод
Риски и недостающие данные
Что делать
Всегда различай Gross profit, Net profit, Operating/Free cash flow и деньги, потенциально доступные собственнику.
Положительная прибыль не означает наличие денег. Отрицательный Contribution означает, что рост продаж может ухудшать результат.
Не называй финансовую целевую цену гарантированно рыночной или рекомендуемой без рыночных данных.
Изменения разрешены только через snapshot.allowedActions. Не меняй данные скрыто.
Каждое изменение — отдельный action с понятной причиной. Калькулятор покажет его пользователю и применит только после подтверждения.
Если allowActions=false, верни пустой actions либо один action type="none".
Если данных недостаточно, укажи это в warnings и не подставляй догадки.
Это управленческая оценка, а не бухгалтерское, налоговое или юридическое заключение.
Верни только JSON по заданной схеме.`;
function extractJsonObject(text){if(typeof text!=='string')throw new Error('Model returned no text');let cleaned=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');try{return JSON.parse(cleaned)}catch{}const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start>=0&&end>start)return JSON.parse(cleaned.slice(start,end+1));throw new Error('Model output was not valid JSON')}
function normalizeResult(data,allowActions){const out=data&&typeof data==='object'?data:{},answer=String(out.answer||'Ответ не получен.'),warnings=Array.isArray(out.warnings)?out.warnings.map(String).slice(0,20):[];let actions=Array.isArray(out.actions)?out.actions:[];actions=actions.filter(a=>a&&actionTypes.includes(a.type)).slice(0,30).map(a=>({type:String(a.type),target:String(a.target||''),field:String(a.field||''),value_text:String(a.value_text??''),reason:String(a.reason||'')}));if(!allowActions)actions=[];return {answer,warnings,actions}}
function openAIOutputText(data){if(typeof data.output_text==='string')return data.output_text;for(const item of data.output||[])for(const part of item.content||[])if(part?.type==='output_text')return part.text||'';return ''}
async function callOpenAI(question,snapshot,allowActions){if(!OPENAI_API_KEY)throw Object.assign(new Error('OPENAI_API_KEY is not configured'),{statusCode:503});const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,store:false,instructions,input:JSON.stringify({question,allowActions,snapshot}),max_output_tokens:2400,text:{format:{type:'json_schema',name:'calculator_assistant_response',strict:true,schema:responseSchema}}})});const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{data={error:{message:raw.slice(0,1000)}}}if(!response.ok)throw Object.assign(new Error(data?.error?.message||`OpenAI API error ${response.status}`),{statusCode:response.status>=500?502:400});return normalizeResult(extractJsonObject(openAIOutputText(data)),allowActions)}
async function callOpenRouter(question,snapshot,allowActions){if(!OPENROUTER_API_KEY)throw Object.assign(new Error('OPENROUTER_API_KEY is not configured'),{statusCode:503});const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':'https://kclsurvey.github.io/survey/margin-calculators/','X-OpenRouter-Title':'Margin Calculators v9.1 and v10.1'},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:instructions},{role:'user',content:JSON.stringify({question,allowActions,snapshot})}],temperature:0.1,max_tokens:2400,response_format:{type:'json_object'}})});const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{data={error:{message:raw.slice(0,1000)}}}if(!response.ok)throw Object.assign(new Error(data?.error?.message||`OpenRouter API error ${response.status}`),{statusCode:response.status>=500?502:400});const content=data?.choices?.[0]?.message?.content,text=Array.isArray(content)?content.map(x=>x?.text||'').join(''):String(content||'');return normalizeResult(extractJsonObject(text),allowActions)}
async function callProvider(question,snapshot,allowActions){if(PROVIDER==='openai')return callOpenAI(question,snapshot,allowActions);if(PROVIDER==='openrouter')return callOpenRouter(question,snapshot,allowActions);throw Object.assign(new Error('AI_PROVIDER must be openai or openrouter'),{statusCode:503})}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin||'';if(!isAllowedOrigin(origin)){sendJson(res,403,{error:'Origin is not allowed'},origin);return}if(req.method==='OPTIONS'){res.writeHead(204,corsHeaders(origin));res.end();return}const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/health'){const keyConfigured=PROVIDER==='openai'?Boolean(OPENAI_API_KEY):Boolean(OPENROUTER_API_KEY);sendJson(res,200,{ok:true,provider:PROVIDER,model:MODEL,keyConfigured},origin);return}if(req.method==='POST'&&url.pathname==='/api/assistant'){if(!rateAllowed(req.socket.remoteAddress||'unknown')){sendJson(res,429,{error:'Too many requests. Try again in a minute.'},origin);return}try{const body=await readJson(req),question=String(body.question||'').trim(),snapshot=body.snapshot;if(!question)throw Object.assign(new Error('question is required'),{statusCode:400});if(!snapshot||typeof snapshot!=='object')throw Object.assign(new Error('snapshot is required'),{statusCode:400});sendJson(res,200,await callProvider(question,snapshot,body.allowActions!==false),origin)}catch(e){console.error(new Date().toISOString(),e.message);sendJson(res,e.statusCode||500,{error:e.message||'Internal server error'},origin)}return}sendJson(res,404,{error:'Not found'},origin)});server.listen(PORT,()=>{console.log(`Calculator AI proxy: http://localhost:${PORT}`);console.log(`Provider: ${PROVIDER}; model: ${MODEL}`);console.log(`Key configured: ${PROVIDER==='openai'?Boolean(OPENAI_API_KEY):Boolean(OPENROUTER_API_KEY)}`)});